name: Express Server Testing

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  runs_server_tests:
    name: Run server tests
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Clone repo to Actions
        uses: actions/checkout@v3

      - name: Set up NodeJS on Actions computer
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install server dependencies
        run: npm install

      - name: Run tests
        run: npm run test-ci
